name: Mcribbl
version: ${project.version}
main: xyz.haoteng.mcribbl.Mcribbl
api-version: 1.16
authors: [ HaoTeng ]
website: haoteng.xyz
commands:
  color:
    description: modify the color
  start:
    description: start drawing